<?php echo $this->doctype(); ?>

<html lang="<?= $this->lang() ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AppLocalization</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/responsive.css">
</head>
<body>
    <div id="content">
        <?php echo $this->content; ?>
    </div>
<?php echo $this->inlineScript() ?>
</body>
</html>
