<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Greenvillage</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico">
    <link rel="stylesheet" href="css/new_style.css">
    <link rel="stylesheet" href="css/responsive.css">
</head>
<body class="body-home-page">
    <?= $this->Header(); ?>
    <!-- <section id="slideshow" class="sm-hidden home-main-slider"> -->
    <div class="home-main-video">
        <video autoplay loop>
            <source src="video/Default.webm">
                <source src="video/Default.mp4">
                    <source src="video/Default.ogv">
                    </video>
                </div>
                <section id="home-slideshow" class="sm-hidden">
                    <img src="./images/1.jpg" data-mfp-src="./images/1.jpg" />
                </section>
                <!-- </section> -->
                <section id="content-wrapper">
                    <div id="content">
                        <?php echo $this->content; ?>
                    </div>
                </section>
                <?= $this->Footer(); ?>
                <script src="js/jquery-2.1.3.min.js"></script>
                <script src="js/zepto.js" type="text/javascript"></script>
                <script src="js/anyslider.min.js" type="text/javascript"></script>
                <script src="js/script.js" type="text/javascript"></script>
                <script>
                    $(document).ready(function() {
                        $("#slideshow").anyslider({
                            showControls: false,
                            showBullets: false,
                            animation: 'fade',
                            speed: 1500
                        });
                        var $video = $('#homeVideo');
                        $video.on('canplaythrough', function() {
                            this.play();
                        });
                    });
                </script>
                <script>
        // form Ajax
        $(document).ready(function() {
            var callBackSubmitBtn = $('#callback-dialog .callback-submit');

            callBackSubmitBtn.on('click', function(event) {
                event.preventDefault();
                
                
                $.ajax({
                    url: '<?= $this->url('localization/send-email', ['lang' => $this->lang()]); ?>',
                    type: 'POST',
                    dataType: 'default: Intelligent Guess (Other values: xml, json, script, or html)',
                    data: {
						"name" 			: $("input[name='name']").val(),
						"phone" 		: $("input[name='phone']").val(),
						"pretty_time" 	: $("input[name='pretty_time']").val(),
						"msg" 			: $("input[name='msg']").val(),
                    	},
                })
                .always(function( data) {
                    console.log("complete", data);
                });

                $('#callback-dialog')[0].style.visibility = 'hidden';
                var inputs = document.querySelectorAll('#callback-dialog input');
                for (var i = 0; i < inputs.length; i++) {
                    inputs[i].value = '';
                }
            });

        });
// END:form Ajax
</script>
<?php echo $this->inlineScript() ?>
</body>
</html>
